from flask import Flask, render_template_string
import json
import os
 
app = Flask(__name__)
 
# Path to the JSON report generated by main.py
REPORT_PATH = os.path.join("output", "ioc_report.json")
 
 
# ---- HTML template (inline so no separate folder needed) ----
HTML = """
<!DOCTYPE html>
<html>
<head>
  <title>IOC Threat Feed Dashboard</title>
  <style>
    body { font-family: Arial, sans-serif; background: #0f0f0f; color: #e0e0e0; padding: 20px; }
    h1 { color: #00ff99; font-size: 22px; }
    .meta { color: #888; font-size: 13px; margin-bottom: 20px; }
    .stats { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
    .stat-card {
      background: #1a1a1a; border: 1px solid #2a2a2a;
      border-radius: 8px; padding: 14px 20px; min-width: 120px;
    }
    .stat-num { font-size: 28px; font-weight: bold; color: #00ff99; }
    .stat-label { font-size: 12px; color: #888; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #1a1a1a; padding: 10px 12px; text-align: left; color: #aaa; border-bottom: 1px solid #2a2a2a; }
    td { padding: 9px 12px; border-bottom: 1px solid #1a1a1a; word-break: break-all; }
    tr:hover td { background: #1a1a1a; }
    .sev { padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
    .CRITICAL { background: #4a0000; color: #ff4444; }
    .HIGH     { background: #3a2000; color: #ff9933; }
    .MEDIUM   { background: #2a2a00; color: #ffdd00; }
    .LOW      { background: #002a00; color: #44ff44; }
    .search { margin-bottom: 16px; }
    .search input {
      background: #1a1a1a; border: 1px solid #2a2a2a; color: #e0e0e0;
      padding: 8px 12px; border-radius: 6px; width: 300px; font-size: 13px;
    }
    .no-report { color: #ff4444; background: #1a1a1a; padding: 16px; border-radius: 8px; }
  </style>
</head>
<body>
  <h1>🛡️ IOC Threat Feed Dashboard</h1>
 
  {% if error %}
    <div class="no-report">
      {{ error }}<br><br>
      Run <code>python3 main.py</code> first to generate the report.
    </div>
  {% else %}
    <div class="meta">Generated: {{ generated_at }} &nbsp;|&nbsp; Total IOCs: {{ total }}</div>
 
    <div class="stats">
      {% for sev, count in by_severity.items() %}
      <div class="stat-card">
        <div class="stat-num">{{ count }}</div>
        <div class="stat-label">{{ sev }}</div>
      </div>
      {% endfor %}
      {% for t, count in by_type.items() %}
      <div class="stat-card">
        <div class="stat-num">{{ count }}</div>
        <div class="stat-label">{{ t }}</div>
      </div>
      {% endfor %}
    </div>
 
    <div class="search">
      <input type="text" id="searchBox" onkeyup="filterTable()" placeholder="Search IOCs...">
    </div>
 
    <table id="iocTable">
      <thead>
        <tr>
          <th>Value</th>
          <th>Type</th>
          <th>Severity</th>
          <th>Feed Count</th>
          <th>Sources</th>
        </tr>
      </thead>
      <tbody>
        {% for ioc in iocs %}
        <tr>
          <td>{{ ioc.value }}</td>
          <td>{{ ioc.type }}</td>
          <td><span class="sev {{ ioc.severity }}">{{ ioc.severity }}</span></td>
          <td>{{ ioc.feed_count }}</td>
          <td>{{ ioc.sources | join(', ') }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
 
  <script>
    function filterTable() {
      const query = document.getElementById('searchBox').value.toLowerCase();
      const rows = document.querySelectorAll('#iocTable tbody tr');
      rows.forEach(row => {
        row.style.display = row.textContent.toLowerCase().includes(query) ? '' : 'none';
      });
    }
  </script>
</body>
</html>
"""
 
 
@app.route("/")
def dashboard():
    """Main dashboard page — reads ioc_report.json and renders it."""
 
    # Check if the report file exists
    if not os.path.exists(REPORT_PATH):
        return render_template_string(HTML,
            error="Report file not found: output/ioc_report.json",
            iocs=[], generated_at="", total=0,
            by_severity={}, by_type={}
        )
 
    # Load the JSON report
    try:
        with open(REPORT_PATH, "r") as f:
            data = json.load(f)
    except Exception as e:
        return render_template_string(HTML,
            error=f"Error reading report: {e}",
            iocs=[], generated_at="", total=0,
            by_severity={}, by_type={}
        )
 
    # Count by severity and type for the stat cards
    by_severity = {}
    by_type = {}
    for ioc in data.get("iocs", []):
        sev = ioc.get("severity", "UNKNOWN")
        t   = ioc.get("type", "unknown")
        by_severity[sev] = by_severity.get(sev, 0) + 1
        by_type[t]       = by_type.get(t, 0) + 1
 
    return render_template_string(HTML,
        iocs=data.get("iocs", []),
        generated_at=data.get("generated_at", "unknown"),
        total=data.get("total_iocs", 0),
        by_severity=by_severity,
        by_type=by_type,
        error=None
    )
 
 
if __name__ == "__main__":
    # debug=True auto-reloads when you edit the file
    # host='0.0.0.0' makes it accessible from other machines on the network
    app.run(debug=True, host="0.0.0.0", port=5000)
 
